<section class="home-container">
    <div class="home-content">
        <h1>3WA Tasks</h1>
        <h2>The best way to optimize your time</h2>
        
        <p>
            Based on the Eisenhower method, our application gives you the best order 
            to do what you have to do. Manage your priorities easily: organize, plan, delegate.
        </p>

        <div class="home-btn">
            <a href="register.php" class="btn btnregister">Register</a>
            <a href="login.php" class="btn btnlogin">Login</a>
        </div>
    </div>

    <div class="home-illustration">
        <img src="assets/image/image.png" alt="Illustration To Do List">
    </div>
</section>