<div class="login-page">
    <div class="login-card">
        <h2>Login</h2>
        
        <?php if (isset($_SESSION['flash'])) : ?>
            <div class="message success">
                <i class="fa-solid fa-circle-check"></i>
                <p><?= $_SESSION['flash']; ?></p>
            </div>
            <?php unset($_SESSION['flash']); ?>
        <?php endif; ?>

        <form method="post" action="login.php">
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" id="username" name="username" required>
            </div>

            <div class="form-group">
                <label for="new-password">Password :</label>
                <div class="password-wrapper">
                    <input type="password" id="password" name="password" required>
                    <i class="fa-regular fa-eye" id="togglePassword"></i>
                </div>
            </div>

            <button type="submit" class="btn-submit">Login</button>
        </form>

        <?php if (isset($error)) : ?>
            <div class="message error">
                <i class="fa-solid fa-circle-exclamation"></i>
                <p><?= $error; ?></p>
            </div>
        <?php endif; ?>
        
        <p class="switch-auth">Don't have an account yet ? <a href="register.php">Register</a></p>
    </div>
</div>